local _, ns = ...

-- GENERATED by scripts/bake_harvest.py from an in-game harvest.
-- Do not edit by hand: re-run the script against your SavedVariables file.
-- Effects, exclusive-with lines and skill levels stay in Data.lua; this file
-- only carries what the client itself told us.
ns.Data = ns.Data or {}
ns.Data.harvested = {
    ["Basic Campfire"] = {
        spellID = 1229737,
        itemID = 279981,
        creates = 1,
        reagents = {
            { itemID = 4470, name = "Simple Wood", count = 1 },
        },
    },
    ["Expert Campfire"] = {
        spellID = 1291341,
        itemID = 279974,
        creates = 1,
        reagents = {
            { itemID = 272941, name = "Thick Logs", count = 1 },
        },
    },
    ["First Aid Kit"] = {
        spellID = 1230117,
        itemID = 279968,
        creates = 1,
        reagents = {
            { itemID = 1251, name = "Linen Bandage", count = 3 },
            { itemID = 159, name = "Refreshing Spring Water", count = 1 },
        },
    },
    ["Fish Bowl"] = {
        spellID = 1229745,
        itemID = 279967,
        creates = 1,
        reagents = {
            { itemID = 6291, name = "Raw Brilliant Smallfish", count = 1 },
            { itemID = 3371, name = "Empty Vial", count = 1 },
        },
    },
    ["Fishing Hut"] = {
        spellID = 1262998,
        itemID = 279966,
        creates = 1,
        reagents = {
            { itemID = 4470, name = "Simple Wood", count = 5 },
            { itemID = 14048, name = "Bolt of Runecloth", count = 2 },
            { itemID = 273295, name = "Seasonal Fish Steaks", count = 1 },
        },
    },
    ["Fishing Rack"] = {
        spellID = 1262990,
        itemID = 279965,
        creates = 1,
        reagents = {
            { itemID = 4470, name = "Simple Wood", count = 2 },
            { itemID = 8925, name = "Crystal Vial", count = 1 },
            { itemID = 8365, name = "Raw Mithril Head Trout", count = 2 },
        },
    },
    ["Greenhouse"] = {
        spellID = 1262980,
        itemID = 279964,
        creates = 1,
        reagents = {
            { itemID = 4470, name = "Simple Wood", count = 2 },
            { itemID = 8836, name = "Arthas' Tears", count = 1 },
            { itemID = 8831, name = "Purple Lotus", count = 1 },
        },
    },
    ["Incense Candle"] = {
        spellID = 1229705,
        itemID = 279962,
        creates = 1,
        reagents = {
            { itemID = 2447, name = "Peacebloom", count = 1 },
            { itemID = 765, name = "Silverleaf", count = 1 },
        },
    },
    ["Iron Oven"] = {
        spellID = 1263067,
        itemID = 279982,
        creates = 1,
        reagents = {
            { itemID = 10284, name = "Simple Flour", count = 10 },
            { itemID = 159, name = "Refreshing Spring Water", count = 5 },
            { itemID = 3713, name = "Soothing Spices", count = 4 },
        },
    },
    ["Journeyman Campfire"] = {
        spellID = 1283400,
        itemID = 279961,
        creates = 1,
        reagents = {
            { itemID = 11291, name = "Star Wood", count = 1 },
        },
    },
    ["Lodestone"] = {
        spellID = 1230161,
        itemID = 279960,
        creates = 1,
        reagents = {
            { itemID = 2835, name = "Rough Stone", count = 1 },
            { itemID = 2840, name = "Copper Bar", count = 1 },
        },
    },
    ["Molten Foundry"] = {
        spellID = 1263071,
        itemID = 279952,
        creates = 1,
        reagents = {
            { itemID = 12359, name = "Thorium Bar", count = 5 },
            { itemID = 12365, name = "Dense Stone", count = 2 },
            { itemID = 6037, name = "Truesilver Bar", count = 1 },
        },
    },
    ["Plague Doctor's Laboratory"] = {
        spellID = 1263001,
        itemID = 279951,
        creates = 1,
        reagents = {
            { itemID = 4470, name = "Simple Wood", count = 2 },
            { itemID = 6453, name = "Strong Anti-Venom", count = 2 },
            { itemID = 14530, name = "Heavy Runecloth Bandage", count = 5 },
        },
    },
    ["Rock Garden"] = {
        spellID = 1262975,
        itemID = 279948,
        creates = 1,
        reagents = {
            { itemID = 2838, name = "Heavy Stone", count = 2 },
            { itemID = 2772, name = "Iron Ore", count = 1 },
            { itemID = 2842, name = "Silver Bar", count = 1 },
        },
    },
    ["Seed Hybridizer"] = {
        spellID = 1263070,
        itemID = 279947,
        creates = 1,
        reagents = {
            { itemID = 13465, name = "Mountain Silversage", count = 4 },
            { itemID = 8925, name = "Crystal Vial", count = 1 },
            { itemID = 14047, name = "Runecloth", count = 2 },
        },
    },
    ["Toxin Study"] = {
        spellID = 1262996,
        itemID = 279940,
        creates = 1,
        reagents = {
            { itemID = 6452, name = "Anti-Venom", count = 1 },
            { itemID = 8544, name = "Mageweave Bandage", count = 2 },
            { itemID = 4470, name = "Simple Wood", count = 2 },
        },
    },
}
