"""Turn the in-game harvest into Fireside/Harvested.lua.

The addon writes real recipe IDs, output item IDs and reagents into its
SavedVariables while you play (see Probe.lua). This script reads that file and
regenerates the generated data block the addon ships with, so a fresh install
knows the right IDs without opening a single profession window.

Usage:
    python scripts/bake_harvest.py "D:/Games/World of Warcraft/_classic_beta_/WTF/Account/<id>/SavedVariables/Fireside.lua"
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "Harvested.lua"


class LuaParser:
    """Just enough of the Lua table syntax to read a SavedVariables file."""

    TOKEN = re.compile(
        r"""\s*(?:
            (?P<string>"(?:[^"\\]|\\.)*")
          | (?P<number>-?\d+(?:\.\d+)?(?:e[+-]?\d+)?)
          | (?P<name>[A-Za-z_][A-Za-z_0-9]*)
          | (?P<symbol>[\{\}\[\]=,])
        )""",
        re.VERBOSE | re.IGNORECASE,
    )

    def __init__(self, text):
        self.text = text
        self.pos = 0

    def next_token(self):
        match = self.TOKEN.match(self.text, self.pos)
        if not match:
            return None
        self.pos = match.end()
        return match

    def peek_token(self):
        start = self.pos
        token = self.next_token()
        self.pos = start
        return token

    def parse_value(self):
        token = self.next_token()
        if token is None:
            raise ValueError("unexpected end of file")
        if token.group("string"):
            return token.group("string")[1:-1].encode().decode("unicode_escape")
        if token.group("number"):
            text = token.group("number")
            return float(text) if ("." in text or "e" in text.lower()) else int(text)
        if token.group("name"):
            name = token.group("name")
            if name == "true":
                return True
            if name == "false":
                return False
            if name == "nil":
                return None
            raise ValueError(f"unexpected identifier {name}")
        if token.group("symbol") == "{":
            return self.parse_table()
        raise ValueError(f"unexpected token {token.group(0)!r}")

    def parse_table(self):
        table, array = {}, []
        while True:
            token = self.next_token()
            if token is None:
                raise ValueError("unterminated table")
            symbol = token.group("symbol")
            if symbol == "}":
                return table if table else array
            if symbol == ",":
                continue
            if symbol == "[":
                key = self.parse_value()
                self.next_token()  # ]
                self.next_token()  # =
                table[key] = self.parse_value()
                continue
            # positional value
            self.pos = token.start()
            array.append(self.parse_value())


def load_saved_variables(path):
    text = Path(path).read_text(encoding="utf-8")
    text = text.split("=", 1)[1]  # drop "FiresideDB ="
    parser = LuaParser(text)
    parser.next_token()  # opening {
    return parser.parse_table()


def lua_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(recipes):
    lines = [
        "local _, ns = ...",
        "",
        "-- GENERATED by scripts/bake_harvest.py from an in-game harvest.",
        "-- Do not edit by hand: re-run the script against your SavedVariables file.",
        "-- Effects, exclusive-with lines and skill levels stay in Data.lua; this file",
        "-- only carries what the client itself told us.",
        "ns.Data = ns.Data or {}",
        "ns.Data.harvested = {",
    ]

    for name in sorted(recipes):
        record = recipes[name]
        lines.append("    [%s] = {" % lua_quote(name))
        lines.append("        spellID = %d," % record["recipeID"])
        if record.get("outputItemID"):
            lines.append("        itemID = %d," % record["outputItemID"])
        if record.get("quantityMin"):
            lines.append("        creates = %d," % record["quantityMin"])
        reagents = record.get("reagents") or []
        if reagents:
            lines.append("        reagents = {")
            for reagent in reagents:
                lines.append(
                    "            { itemID = %d, name = %s, count = %d },"
                    % (reagent["itemID"], lua_quote(reagent.get("name") or "?"), reagent.get("quantity", 1))
                )
            lines.append("        },")
        lines.append("    },")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1

    db = load_saved_variables(sys.argv[1])
    recipes = db.get("harvest", {}).get("recipes", {})
    if not recipes:
        print("No harvested recipes in that file.")
        return 1

    OUT.write_text(render(recipes), encoding="utf-8")
    print(f"{len(recipes)} recipe(s) written to {OUT}")
    for name in sorted(recipes):
        record = recipes[name]
        print(f"  {name}: spell {record['recipeID']}, item {record.get('outputItemID')}, "
              f"{len(record.get('reagents') or [])} reagent(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
